.TH nologind 8 "28 October 2018" "20181028" "nologind documentation"
.SH NAME
nologind -\ logind wrapper for ConsoleKit
.SH SYNOPSIS
nologind
.SH DESCRIPTION
A logind wrapper for ConsoleKit(2) on Slackware. Used as a compatibility layer for applications that require (parts of) the org.freedesktop.login1.Manager D-Bus system service.

.SH BUGS
See https://github.com/rodlie/nologind/issues

.SH AUTHOR
Ole-André Rodlie (ole.andre.rodlie@gmail.com)

.SH COPYRIGHT
Available under the 3-clause BSD license.
